apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'order-service-dev'
        static_configs:
          - targets: ['order-service.dev.svc.cluster.local:3002']
        metrics_path: /health

      - job_name: 'product-service-dev'
        static_configs:
          - targets: ['product-service.dev.svc.cluster.local:3001']
        metrics_path: /health

      - job_name: 'frontend-dev'
        static_configs:
          - targets: ['ecommerce-frontend.dev.svc.cluster.local:3000']
        metrics_path: /health
