apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: dev
  labels:
    environment: dev
    project: ecommerce
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: staging
  labels:
    environment: staging
    project: ecommerce
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: prod
  labels:
    environment: prod
    project: ecommerce
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
