apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    project: ecommerce
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    project: ecommerce
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    project: ecommerce
    managed-by: kubectl
